import express from 'express';
import multer from 'multer';
import fs from 'node:fs/promises';
import { mkdtemp } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const exec = promisify(execFile);
const app = express();
const MAX_FILE_SIZE = 500 * 1024 * 1024;
app.use((req,res,next)=>{res.setHeader('Access-Control-Allow-Origin',process.env.ALLOWED_ORIGIN||'*');res.setHeader('Access-Control-Allow-Methods','POST,OPTIONS,GET');res.setHeader('Access-Control-Allow-Headers','Content-Type');next()});
app.options('*',(req,res)=>res.sendStatus(204));
const upload = multer({dest:os.tmpdir(),limits:{fileSize:MAX_FILE_SIZE,files:3}});
app.get('/health',(req,res)=>res.json({ok:true,maxFileSize:MAX_FILE_SIZE}));
app.post('/sign',upload.fields([{name:'ipa',maxCount:1},{name:'p12',maxCount:1},{name:'profile',maxCount:1}]),async(req,res)=>{let dir;const uploaded=Object.values(req.files||{}).flat();const cleanup=async()=>{if(dir)await fs.rm(dir,{recursive:true,force:true}).catch(()=>{});await Promise.all(uploaded.map(f=>f?.path?fs.rm(f.path,{force:true}).catch(()=>{}):null))};try{const ipa=req.files?.ipa?.[0],p12=req.files?.p12?.[0],profile=req.files?.profile?.[0];if(!ipa||!p12||!profile)return res.status(400).send('IPA, P12, and provisioning profile are required.');dir=await mkdtemp(path.join(os.tmpdir(),'ipa-signer-'));const inIpa=path.join(dir,'input.ipa'),cert=path.join(dir,'cert.p12'),prov=path.join(dir,'profile.mobileprovision'),out=path.join(dir,'signed.ipa');await Promise.all([fs.copyFile(ipa.path,inIpa),fs.copyFile(p12.path,cert),fs.copyFile(profile.path,prov)]);await cleanup();await exec('zsign',['-k',cert,'-p',req.body.password||'','-m',prov,'-o',out,inIpa],{timeout:600000,maxBuffer:1024*1024});res.download(out,'signed.ipa',async()=>{if(dir)await fs.rm(dir,{recursive:true,force:true}).catch(()=>{})})}catch(err){console.error(err);await cleanup();if(err?.code==='LIMIT_FILE_SIZE')return res.status(413).send('File exceeds the 500 MB maximum.');res.status(500).send('Signing failed. Check the certificate, password, provisioning profile, and IPA.')}});
app.use((err,req,res,next)=>{console.error(err);if(err?.code==='LIMIT_FILE_SIZE')return res.status(413).send('File exceeds the 500 MB maximum.');res.status(400).send('Invalid upload.')});
app.listen(process.env.PORT||3000,()=>console.log('IPA signer backend running; max IPA size: 500 MB'));
